# Generated by Django 2.2.26 on 2022-02-01 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evangelisation', '0003_auto_20220201_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evangelisation',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, error_messages={'unique': "ce moment d'évangelisation existe déjà"}, unique=True, verbose_name="Jour d'évangélisation"),
        ),
    ]
