# Generated by Django 2.2.26 on 2022-02-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evangelisation', '0004_auto_20220201_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivi',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='evangelisation.Person', verbose_name='Personne'),
        ),
    ]
