# Generated by Django 2.2.26 on 2022-02-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelisation', '0005_auto_20220205_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contacts',
            field=models.PositiveIntegerField(blank=True, default=0, error_messages={'unique': 'Le numéro de télephone existe déjà'}, help_text='Le numéro de téléphone doit avoir 09 chiffres', null=True, unique=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='quartier_d_habitation',
            field=models.CharField(blank=True, default=0, help_text='ce champ doit avoir au moins trois caractères', max_length=200, null=True, verbose_name="Quartier d'habitation"),
        ),
    ]
