# Generated by Django 2.2.26 on 2022-02-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelisation', '0006_auto_20220208_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='quartier_d_habitation',
            field=models.CharField(blank=True, default='---', help_text='ce champ doit avoir au moins trois caractères', max_length=200, null=True, verbose_name="Quartier d'habitation"),
        ),
    ]
