# Generated by Django 2.2.26 on 2022-02-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelisation', '0007_auto_20220208_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contacts',
            field=models.PositiveIntegerField(blank=True, error_messages={'unique': 'Le numéro de télephone existe déjà'}, help_text='Le numéro de téléphone doit avoir 09 chiffres', null=True, unique=True, verbose_name='Numéro de téléphone'),
        ),
    ]
