# Generated by Django 2.2.26 on 2022-02-08 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evangelisation', '0009_auto_20220208_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivi',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivi', to='evangelisation.Person', verbose_name='Personne'),
        ),
    ]
